### ISSUE TITLE
请问作者们有尝试过增大和谐化图片的尺寸吗？

### ISSUE THREAD

**Issue by countingeyes** [bcmi/PHDNet-Painterly-Image-Harmonization#10]
作者你好，想请问下你们有尝试过增大和谐化图片的尺寸吗？我想在和谐化问题后面接识别和分割的应用，发现大多数的和谐化工作都在256×256的尺寸上进行，实验后resize或者简单超分会导致图片质量非常差，对下游应用来说还不太够用。想请教下作者，这块可以有什么处理思路呢？单纯改卷积尺寸可行吗？

**Comment by ustcnewly** [comment]
标准的图像和谐化可以支持任意分辨率的图片，https://github.com/bcmi/libcom 里面集成了两个图像和谐化方法CDTNet和PCTNet, 都可以做任意分辨率。
艺术图像和谐化，我们的一个工作https://github.com/bcmi/PHDiffusion-Painterly-Image-Harmonization 能做到512x512,

**Comment by countingeyes** [comment]
非常感谢！
