### ISSUE TITLE
本地图像和谐

### ISSUE THREAD

**Issue by chen8573** [bcmi/PHDNet-Painterly-Image-Harmonization#2]
作者您好，感谢您的工作，请问是否可以提供用于本地图片和谐的demo呢

**Comment by cjy-4** [comment]
Hi. We have provided the test scripts for your custom test data. Please fill in the corresponding parameters in `scripts/test_custom.sh` and then run it.
Thanks for your attention.

**Comment by cjy-4** [comment]
> 作者您好，感谢您的工作，请问是否可以提供用于本地图片和谐的demo呢

Hi. We have provided the test scripts for your custom test data. Please fill in the corresponding parameters in `scripts/test_custom.sh` and then run it.
Thanks for your attention.
