### ISSUE TITLE
Questions regarding download link and input size

### ISSUE THREAD

**Issue by kts707** [bcmi/PHDNet-Painterly-Image-Harmonization#3]
Hi,

Thanks for the great work and the results look amazing! 

For the pre-trained model [here](https://pan.baidu.com/s/1D6iAS6Sli1QggLp-E9EvyQ), is it possible to also share it on other platforms such as Google Drive? The Baidu Cloud keeps asking me to download its own app instead of the actual pre-trained model. Much appreaciated!

Also does the code strictly requires square images as input? Or does it work on any arbitrary input image resolutions? Thanks a lot!

**Comment by cjy-4** [comment]
Thanks for your attention.

We share the pre-trained model on [Google Drive](https://drive.google.com/drive/folders/1dAuUFMjRr3mxAaDkvXQzLBjMyIjNIZsC) now.

Currently the code strictly requires square images as input. 

> Hi,
> 
> Thanks for the great work and the results look amazing!
> 
> For the pre-trained model [here](https://pan.baidu.com/s/1D6iAS6Sli1QggLp-E9EvyQ), is it possible to also share it on other platforms such as Google Drive? The Baidu Cloud keeps asking me to download its own app instead of the actual pre-trained model. Much appreaciated!
> 
> Also does the code strictly requires square images as input? Or does it work on any arbitrary input image resolutions? Thanks a lot!

**Comment by kts707** [comment]
Thanks for sharing on Google Drive and for the details regarding the input size!
