### ISSUE TITLE
复现不能达到文章的效果

### ISSUE THREAD

**Issue by jokerktf** [bcmi/PHDNet-Painterly-Image-Harmonization#4]
用项目提供的预训练模型的到的图像，效果很差，带有蓝绿色的噪声纹理，例如：
![15971a62a370f6f2b10ee7db5903534](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/143123287/ca43325f-af0c-4d26-b0fa-02966cdcba6b)
![5bd0370da91409d9840157888c992db](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/143123287/b25fa6ed-9abc-4d96-887f-19fbd1290d19)
不知道问题出现在哪里，能否给予指导

**Comment by cjy-4** [comment]
Hi, thanks for your attention.
It seemed that the pre-trained model was failed to load during the test phase, which resulted in the results you attached.
When you run the test codes, the options would be printed on the terminal (see the screenshot below). You could check if the pre-trained model was successfully loaded.

![info](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/59011028/4bb498ea-175a-432a-8e10-608c0b6c35a9)

Please check if you modify the parameters in `scripts/test_phd.sh` to your local path.
