### ISSUE TITLE
训练过程中出现噪声不知道如何处理请问能否给与指导

### ISSUE THREAD

**Issue by guohanp** [bcmi/PHDNet-Painterly-Image-Harmonization#7]
![image](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/140575001/add0751d-a280-4be2-b88b-93347efc3c38)

**Comment by cjy-4** [comment]
Try to increase the value of `L_GAN` in `scripts/train_phd.sh`.

**Comment by guohanp** [comment]
谢谢

**Comment by guohanp** [comment]
增大L_GAN到25后观察到判别器损失依旧在快速下降请问是正常的吗能否给与指导 
![image](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/140575001/a2dab263-695e-4558-927f-1265999104c4)

**Comment by cjy-4** [comment]
Check if there is still artifact in the generated images.

**Comment by guohanp** [comment]
随着训练进行在图片的周围有噪声出现并且逐渐增多

**Comment by guohanp** [comment]
![image](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/140575001/4aa7c30c-989f-41db-af52-d68a8f78d3d1)
100的loss_gan训练到41轮的图片

**Comment by cjy-4** [comment]
L_GAN增大后不需要训这么久，训1~3轮看一下效果。

**Comment by guohanp** [comment]
L_GAN增大后不需要训这么久，训1~3轮是没有噪声的

**Comment by guohanp** [comment]
L_GAN增大后，训1~3轮是没有噪声的

**Comment by guohanp** [comment]
生成的图片效果也还可以但是感觉达不到给的那个权重的水平

**Comment by guohanp** [comment]
![image](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/140575001/e88caf40-09ac-41f3-bc51-b9be8826bf6a)
这是100L_GAN第3轮的图片

**Comment by guohanp** [comment]
请问您当初训了多少轮啊

**Comment by thenotshyshyshy** [comment]
哥在吗请问应该怎么训啊

**Comment by cjy-4** [comment]
先单独训生成器，训15到20轮；再加上判别器训5轮。
