### ISSUE TITLE
您好请问在复现改成中无法达到所给权重的效果应该怎么调整超参数的设置以及大致训练的轮数呢

### ISSUE THREAD

**Issue by thenotshyshyshy** [bcmi/PHDNet-Painterly-Image-Harmonization#8]

**Comment by cjy-4** [comment]
超参调整：如果生成的图片中，前景的内容非常明显，艺术风格与背景还有差异，说明背景的风格迁移不够，需要增大L_S；如果前景的内容基本糊掉了，说明背景的风格迁移过度，需要增大L_C。如果出现明显的artifact，需要增大L_GAN。
我的训练方式：先单独训生成器，训15到20轮；再加上判别器训5轮。

**Comment by thenotshyshyshy** [comment]
感谢

**Comment by thenotshyshyshy** [comment]
您好请问您是怎么单独训练判别器的我注释掉了更新判别器的代码跟判别器损失单独训练生成器的时候，即使增大gan到1500生成的图像到不了15到20轮就出现了明显的artifact，
![Uploading image.png…]()

**Comment by thenotshyshyshy** [comment]
请问鉴别器的梯度不回传单独训生成器15轮的过程出现明显的噪声是什么原因

**Comment by thenotshyshyshy** [comment]
是我注释的不对吗
![image](https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization/assets/149165235/d2369a20-8893-4e51-8297-01ab3645c910)

**Comment by thenotshyshyshy** [comment]
请问您当初训练的参数设置是多少
