### ISSUE TITLE
您好请问有什么客观的指标来评价生成图片的质量吗

### ISSUE THREAD

**Issue by thenotshyshyshy** [bcmi/PHDNet-Painterly-Image-Harmonization#9]

**Comment by ustcnewly** [comment]
可以报的指标很多，比如style loss, content loss, deception rate, CLIP score, DINO score ....,  但是都不怎么靠谱。最靠谱的还是user study。

**Comment by thenotshyshyshy** [comment]
感谢您的回复，请问我如何得到论文中的BT分数

**Comment by ustcnewly** [comment]
按照paper里描述的方式做user study。BT分数反映的是相对排名，比较的baseline不一样，user不一样，分数也不一样。不同paper里的绝对数值不能直接比较。
